name: Cypress API Tests
on: [push]
jobs:
  job1:
    name: cypress-run
    runs-on: ubuntu-latest
    strategy:
            fail-fast: false
            matrix:
             containers: [ 0, 1, 2, 3, 4 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run:  npm install  
      - run:  npx cypress run --env allure=true --spec $(node cypress-parallel.js ${{ matrix.containers }} 5) --browser chrome
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ReportsData
          path: allure-results

#       - name: Get Allure history
#         uses: actions/checkout@v2
#         if: always()
#         continue-on-error: true
#         with:
#           ref: gh-pages
#           path: gh-pages

#       - name: Allure Report action from marketplace
#         uses: simple-elf/allure-report-action@master
#         if: always()
#         #id: allure-report
#         with:
#           allure_results: allure-results
#           #gh_pages: gh-pages
#           # allure_report: allure-report
#           allure_history: allure-history
#           keep_reports: 20

#       - name: Deploy report to Github Pages
#         if: always()
#         uses: peaceiris/actions-gh-pages@v2
#         env:
#           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PUBLISH_BRANCH: gh-pages
#           PUBLISH_DIR: allure-history
        
          
#       - name: Upload Report Data
#         uses: actions/upload-artifact@v3
#         if: always()
#         with:
#           name: allure-results
#           path: allure-results
#       - name: Get Allure history
#         uses: actions/checkout@v2
#         if: always()
#         continue-on-error: true
#         with:
#           ref:  gh-pages
#           path: gh-pages
  
  job2:
    name: reports
    if: always()
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: ReportsData
          path: allure-results 
        
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
